// Full content for each blog post, sourced from djmphotography.blogspot.com
// (fetched via Blogger's post feed API) -- rendered as in-site pages at /blog/:slug
// instead of redirecting out to the external blog.
export const BLOG_POSTS = [
  {
    slug: 'photography-workshop-theatre-of-real-life',
    date: 'Nov 2013',
    tag: 'Workshop',
    title: 'Photography Workshop — The Theatre of Real Life',
    venue: 'DWIH New Delhi — Excellence on Tour, NID Gandhinagar',
    desc: 'A photography workshop led by German photographer Wolfgang Zurborn, held as part of DWIH New Delhi’s "Excellence on Tour" programme strengthening India-Germany cultural exchange.',
    originalHref: 'https://djmphotography.blogspot.com/2013/11/photography-workshop-theatre-of-real.html',
    externalNote: 'wolfgangzurborn.de',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj7gcEQNUajVoA4cDpjOv8YO3arYPlvnFZSDWXvBFjHbNak-AgJhoOn9J9UKKQ1VC0AValG9AEdKAzg0YgybbpX_90Egv9ktJ74UO1SC3u1LvW6ctiwAZh72UjtQnNdVx3P7InceayB6go/s1600/AM+20.11.13.JPG',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjIvHCIcWcwNnFW2gx62VPTF4GJLdTLF2AmrQjx4_BiJ5iGJGdJR7a0jWPwaUUkL2QVbZReQCz_ghT4Pj-xhsjNujqX6-F7SdqRU_NjDqjp1mTybGmypfFrAvJl2VcP18lJbv8-1ef9oF0/s1600/DB+20.11.13.JPG',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjYCJJqJKVNyvC5pJDULyzuVnCfjOHD9MaSFgV4GNoqwENjD16sqbk4JV5wdtsZjgjNFW1ViS7aynVNbXHyvClbvBHWRMsaILTSezRXD4uUsPWPvX4bdxcVPcL-4MGD2gt940n7VPpXxAQ/s1600/GS+20.11.13.JPG',
    ],
    paragraphs: [
      'The photo workshop „The Theatre of Real Life“ by Wolfgang Zurborn was part of the framework programme of the exhibition The DWIH New Delhi – Excellence on Tour!, which has the target to intensify the international cooperation between India and Germany. The workshop set out to experiment with a new view on everyday life, one that does not only confirm what we have known before. Photography gives the chance to react immediately to situations in urban life, to find the intense moments, the surprising constellations of people, objects, signs and architectural spaces in the streets. The choice of themes was totally open and based only on individual interest.',
      'Every photographic perception creates a subjective image of the world — a Theatre of Real Life. In dialogue with others we learn to understand our own photographs, our cultural and social influences. This is the basis for developing a fresh and personal visual language, and it was the main target of the workshop to drive this productive dialogue.',
      'Wolfgang Zurborn was born in 1956 in Ludwigshafen/Rhein. He studied at the Bavarian State School of Photography in Munich from 1977 to 1979 and at the University of Applied Sciences in Dortmund from 1979 to 1984. He received the Otto-Steinert Fellowship of the German Society of Photography (DGPh) in 1985 for his project People Pictures – Picture People, presented in 1987 at the Folkwang Museum in Essen. He has run the Gallery Lichtblick in Cologne for 27 years together with Tina Schelhorn, showing international photography across more than 170 exhibitions, founded the Lichtblick School in 2010, and has served since 1998 on the board of directors of the German Photographic Academy (DFA).',
      'He has taught photography in many different countries, with solo shows of his work presented all over the world, and has participated in important group shows such as "On the Body and other Things — German Photography of the 20th Century." His photographic projects have been the subject of several book publications.',
    ],
  },
  {
    slug: 'journey-into-time-of-maharajas',
    date: 'Dec 2011',
    tag: 'Exhibition',
    title: 'A Journey into the Time of Maharajas',
    venue: 'Supported by Vacheron Constantin',
    desc: 'An exhibition of portraits evoking princely India — each photograph an eloquent record of the majesty and heritage of a world long past, supported by Vacheron Constantin.',
    originalHref: 'https://djmphotography.blogspot.com/2011/12/journey-into-time-of-maharajas.html',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjmyYg_0qYLvJwa3rfAd7LlvMPs0LtdtFND9vK-0ezcvW_056a9fAWntUDaYONHnz-FoH8gGnFYbrYtDye9P7KtML5alT01tvH8sZCHOfN6QcJf8QrOndTlJRVF9xcMAylGFoL6zcgAVGA/s1600/Img+1_Maharaja+Bhim+Singh+of+Kota.jpg',
    ],
    paragraphs: [
      'The photographs in this exhibition are an evocation of princely India and a historical record of an age we will never again experience. Each portrait reflects an unmistakeable aura of majesty, effortlessly carried and eloquently captured. Vacheron Constantin, who supported this exhibition, have a lot in common with the rich heritage the show portrays. For over 250 years Vacheron Constantin has been blending history with innovation, and because of these inherent qualities became one of the preferred suppliers of haute horology and high jewellery timepieces to the Maharajas in the 19th century. Vacheron Constantin can first trace their ties to the Indian market through an order made by J. G. Hanhart from Kolkata in 1849. In the years that followed, many more fine watches were ordered by Maharajas, such as those owned by H.H. Maharaja Sahib Bahadur, H.H. the Maharaja of Jammu and Kashmir, H.H. Maharaja Rana Bahadur of Dholpur and H.H. the Maharaja of Patiala.',
      'The photographic portrait is never truly opaque, and behind the façade of splendid dress and gleaming jewels we glimpse a rare human side to the sitters. As the historian E. Jaiwant Paul noted, ‘the princes of India were undoubtedly one of the great anachronisms of the twentieth century. Among them were enlightened rulers and profligate princes, saints and scoundrels, heroes, charmers and eccentrics.’ The Maharajas in these photographs, whose lineage can be traced back for centuries, mark the end of an epoch in India’s history of ruling principalities. Besides the fabulous palaces, extraordinary jewels and inspired legends these individuals left behind, we have their photographs — some of which are on display here.',
    ],
  },
  {
    slug: 'lens-ing-it-photography-exhibition',
    date: 'May 2011',
    tag: 'Exhibition',
    title: 'Lens-ing It — A Group Exhibition of Photography',
    venue: 'Ashna Gallery, New Delhi · curated by Johny ML',
    desc: 'A group photography exhibition at Ashna Gallery, New Delhi, curated by Johny ML — featuring work alongside Ram Rahman, Sunil Gupta, Vivek Vilasini, and other leading Indian photographers.',
    originalHref: 'https://djmphotography.blogspot.com/2011/05/lens-ing-it-photography-exhibition.html',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgyPjx-zntHmsnVTSrHjQtmk624TTQh0PM5p7sLWYHeV_Dsw0bRFpbRNUy0ag-nDfYR7Wptx1Y50Yel0xBhXKM5f1blPbAe6SJ0yXploSsO5vlTIv1JJy0B41SrqwhG1g1xf5sp2dSMKgw/s1600/Eminent+Photographers+small.jpg',
    ],
    paragraphs: [
      'The show opened at Ashna Gallery on 29th April 2011, curated by Johny ML.',
      'Ashna Singh, director of Ashna Gallery, New Delhi, announced the opening of ‘Lens-ing It’, an exclusive photography show curated by the well-known curator and art critic, Johny ML. ‘Lens-ing It’ opened on 29th April 2011 at the Ashna Gallery, 369 CRC Building, MG Road, Sultanpur, New Delhi, with a seminar on photography taking place the same day from 10 am onwards. The seminar featured Prof. Vinay Lal of Delhi University presenting a keynote paper on "Representing Gandhi: The Practices and Politics of Visual Culture," with the participating artists also making audio-visual presentations.',
      'Participating artists were Alex Fernandes, Ram Rahman, Sunil Gupta, Vivek Vilasini, Abul Kalam Azad, Deepak John Mathew, Anup Mathew Thomas and Manisha Gera Baswani.',
      '“Photography has always been there in the field of fine arts but has always been treated lesser to other forms of art. Today, in the globalized world, photographs have become the message carriers of change. Photographs speak to the people directly and the photography artists have become all the more aware of their worth as meaning makers. For me photographing is a political act,” says Johny ML, curator of ‘Lens-ing It’.',
      '‘Lens-ing It’ has ‘series’ as its thematic orientation. Each artist in the show presents a set of works done with the ‘same mood, sense of reflection and ideological perspective’ within a limited span of time, or within a prolonged period of travel and work undertaken by the artist. The works cohesively hold and display each artist’s innate idea about their medium and the way they use it to ‘produce’ meaning.',
      'Alex Fernandes, through his Tiatriste and Musicians series, searches for the archetypal images that form the cultural make-up of an ethnic community — identifying these archetypes through existing popular and underground cultural forms and bringing them into a studio situation to make them iconic figures within the visual cultural discourse.',
      'Ram Rahman’s oeuvre is quite large, and the series for this show was created out of works done over the last couple of decades. These works show politicians, cultural activists, artists and lawyers as the main images, creating another idea of ‘Delhi’ that manifests in a multitude of forms, situations and people.',
      'Sunil Gupta’s gender politics takes a very dramatic twist in ‘Lens-ing It’ as he opens his gaze upon a lesbian couple, capturing the intimate moments between this loving pair in both domestic and public contexts. Gupta’s positioning as a gay activist underlines his inclusive stance on this selection of images — the aggressive male gaze generally seen in such pictures transforms into a co-traveler’s curious and compassionate registering.',
      'Vivek Vilasini’s ‘Between One Shore and Several Others’ is one of the highly acclaimed series produced by the artist over the last ten years of his career. In it, he painstakingly documents people whose names have nothing to do with their location, personality or profession, recapturing the socio-political and cultural contexts in which these people came to have them. The living people with ‘un-localized’ names achieve a semi-iconic status in these works, emphasizing the contradictions they embody both within their contexts and in an exposed global scenario.',
      'Abul Kalam Azad presents a series of sepia-toned autobiographical pictures that are not pictures from a family album. The small objects spread in and around his studio, partially abandoned by memory, take on the status of museum pieces once registered by the artist — each becoming an icon, culturally encoded and personally inscribed; display items in a museum of memories.',
      'Deepak John Mathew has two series of work in the ‘Lens-ing It’ show. Done over a period of time, the first has images from his home interior and the second has images from an anthropological and historical museum. Seen together, they resonate with the same ideology, tendency and meaning — preserving memories in certain ways, but through various associations also preserving the relationship between the extremes of love and violence.',
      'Anup Mathew Thomas looks at the ways colonialism has taken various manifestations in our contemporary personal lives — the memories and myths that help us form an ‘idea’ about our own lives, working both as history and as an ideological notion. The images he presents carry this history as a soft reminder of achievement and loss, and show how that same history continues to work at an ideological level in our contemporary lives.',
      'Manisha Gera Baswani’s series follows her journey through the lives of artists and art activists within the context of their workplaces. In these photographs, she carefully collapses the idea of a secured private life into the realm of a discursive public by capturing the most unguarded moments from their lives — a silent intrusion that chronicles the lives and times of cultural makers, while speaking to her own idea of looking at artists making and presenting art, both within public and private spheres.',
    ],
  },
  {
    slug: 'photography-design-students-exhibition',
    date: 'Jul 2009',
    tag: 'Exhibition',
    title: 'Photography & Design Students’ Exhibition',
    venue: 'National Institute of Design, Ahmedabad × UCA, Farnham',
    desc: 'Thirteen photography and design students document a cross-cultural exchange abroad, viewing an unfamiliar culture through the keen, objective eye of the camera.',
    originalHref: 'https://djmphotography.blogspot.com/2009/07/photography-design-students-exhibition.html',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjyLi1M8T_RzatCpexMJHAuWbJ76tQ-WrYGkEDV7MRE_9TBDlApmLWGdpJQC_dk6ZJ04Iu3qLDv9UcMrqD7_0QPVoBEp3O2G6CsjcSxeig4cZVZqhAW1KhaxWsXlaew1fRne3QohjZ_H4Q/s1600/MLD_9155.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgTQYoD00b6z8neXddOMUwtu2zY_CSAkp7VQQr251lH0f_BtxzzWkPqQFcCG8WlULnbelYml5hJCFPRCx1DYcZsuzV4ZMnWPDG4UuY8tpI034tpgqVLbkrKx3nvNmXcfGzDw8tf2ZweKbU/s1600/MLD_9130.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEicRhzAcq-YA4bmKCVBtugiYtHefBOgnNT523kKEln-7moAgyiijQXNl5P2PvjTryvmf22Nv89MSxu9AYidyOYsgOepvFC5Fk4Xz4NrhfdtX6EQL8Fw9KFlXN9ronAJs1AhPpgoTSI1beY/s1600/MLD_9201.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjfsWdl43XPz4QWNK_V-YJmDW2mtSRMHpuoZxEejK3b-HSVvhraN6lpCmhveT9s-dtcNabJt-hArC-4RxryIvcsWXFXy7HfL-2tamKMvbpJKR28Bl2tt-LMDkHnfMZwU392HZTrmN0Cr4c/s1600/MLD_9205.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgkGo4Hj1Kh3J57ROBpWEUgzfaPdJiVnV8rdnuFdBNUyAojZ3oUCeF9LZZwivB0S4n2_gO8P2-uxosRgxQLu_7fyUk0B67QRX1rajZuloq5UG83yg66cWjGVaGFBe_fIpJTGYIf6BjpQbg/s1600/MLD_9209.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh8MSLhSrqEnjcN5-DHeRU9mA6FltmcbIPo08cnKPpzu_MvuStWg6ICZJn-uB5vJPSFgMC_Amb6ngmXDi8DHwTxjepjqHxRawSSod_fV-IifPL9-c29fm-9pTNvcrc3P4ZCbDPt7o9DUKs/s1600/MLD_9184.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi1woIq-KooSOkMUed6e54cVqu880yaDs2Gg-hQmH8XKtcd3dN-pra3RqfLmfzs6qzkqbR46ClW_BBO7PqGKC7iHUW8w8JZkz9kiybt6GqLZGtHz3EbfuwM58Sxc06MU1mzONcwjnUD7pU/s1600/MLD_9169.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjhu6byf8hn4Ie164xg1-ZeLddv-TrJo5lz-zFyGRi7Oa5wuts1_lxmhgGRfjPLdyPD_wWUWyGVBvSX8L1iG6DdTtEDL5fBLGAYRDPB9_gkvtJKSUNn0xd6W3pyzeaV67a79wNKhyphenhyphenho00Y/s1600/MLD_9163.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgPC17nu88zlr32HIfQp7wGpxUWrGcNXhyphenhyphenBjHguQwuXkCDskeKq5REU4v251zl7YGnS1gtv0_ial_FBrkafRXNkXVPHix1P1zla70L14sgqwIY85IXSr7m8bp-Zb0WeolxLD8krhIq-yEg/s1600/MLD_9159.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhY9NYSX4w2Vp0BzJV4pv_GPiSXmEqNSWVombrqxH-K1sOHGHuvGFYpLfUcnsK-5qgB5UJjiljJ5cs5U91te_zdWyjZfs2nY8xJg7Flci3Q8DxCigGvls7NvPyn5z3NrWRk_eSMnmJ-IL8/s1600/MLD_9150.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiQpQMcgadnJQItDVZ3jgDmSYh9nUFgfEWHPrMz0GQ-ZBpgiL2-ywQgLPhoDwUkqVtIPhqUKI4DXk2e_4F4ukiuX9_acqrA1s1AV7somDQbSQgIQwVq_m7vHHTXuWw-gN9bObEJtNisn_o/s1600/MLD_9147.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjl6MQIhpxpdj1_aEvpiolTBmZLUa4JCZywP1yolJzDFpp1Um89qaVxDGD3dykM78yMlCeEf8WHUnJy_jtTXxH-X6UTFeW-97DnR3E7ehzeXJmYEB7p5OTU4nwGhHGszdvRBl1Mb7SuOdI/s1600/MLD_9146.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhpd2FGxsQb3B64TqEcNPXDMIONKJZn0oMnPZ4-jiMEXKnBb2Yr0KtwE7LHCkaKjGsNjaAHbW0d-wLI-9JgqG_-xOj1-LCtj-1oQX-Hsk7TDcohxvRn0aiDWaR6-U5SQT56ylz0DfnpE0Y/s1600/MLD_9143.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg_jMyIyoktU5XlspGSkkt57IgdQOL2ReZaKn4di3Gfjx6OiKJwKvqiUoDpmWsdO0-qnaM8bnMtMVTB-Hmk-HhQbAFweBl74fTBh8cwlNMo6cLTWdhSH1cNZt5FwT_sitbFtnCW1HNs9RU/s1600/MLD_9142.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhLqV9VvuP5ByjOuLcpjM-7dMaYYI0Gll-DKfPTNf9Umq2f8pIDbotFXkmcByALo8KTSx33VxQvoP9A2IzROhpxHgTLHiZzGCOpsQM8QsBm3Yt19yiMou1f9G0wPc3vaW3j10O6s9BquAA/s1600/MLD_9131.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgM1QTFIdVIjKbB6Dob88eOOcr86GorvOLDlyqwVfXhLg_hIbyFC47J7cRZR2zm8vBiLleUHHX9cWZroLNANJcg090D44H9UleirH45KkvU5o7tgnWjIT4kwChMGEeIaNiBxkbAC-oHWew/s1600/MLD_9122.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjpNfSb4ZwOZ5gG1ZpDJdaCbuZInpPsnEKbg5BQjs607ZufZtugRKXz1E0PggAKdOkT0zq25J8ZmQBeqnbATuI0uTpgI4keaORjAnx3G7EW9sRRqV8ehYgfm0MhHcjkyk240HkbGvnMSvU/s1600/MLD_9103.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi_8yAyKcuw3XEYVMXqgcbzRe2caNHVH5cZvyQL2F3wAntkoShdn8vzSdzcMYZPwy6nVheQtagewK0qb0s2MRSjB-BMRMAB8IGmzjKMk4CJdtGCWag_GUYHgOvkxX68Rpog4AZtXDVjcyk/s1600/MLD_9097.jpg',
    ],
    paragraphs: [
      'A cross-cultural experience offers a singular opportunity to the photographer; removed from a known cultural context, the unfamiliar culture is viewed from an objective distance through the keen eye of the camera, generating insights and revealing nuances that at times go unnoticed even by the accustomed local. Driven by the desire to understand and interpret this unique experience, thirteen photographers explore concepts like identity and nativity through their photography, in the process making a semblance out of this cultural displacement. The language they use varies from the straightforward aesthetics of documentary or street photography, to the deadpan aesthetics of the posed portrait, to the intuitive outcomes obtained from the alchemical photographic printing process. Spanning photographic genres, this display offers the viewer an intimate dialogue with a distant culture.',
      'This photography display is an outcome of a month-long student exchange programme between the National Institute of Design, Ahmedabad, India, and the University for the Creative Arts, Farnham, United Kingdom. The PGC programme in Photography Design at NID provides students with a creative and intellectual environment to develop their personal aspirations within a community of their peers, and a broader network of artists, designers and other industry professionals. Students are expected to have clear ideas and ambition to make a strong creative statement, and the course builds on individualized photographic practice to promote a rigorous critical and contextual understanding of photographic image-making within the framework of contemporary art and visual communication.',
      'Photography at Farnham is one of Britain’s first photographic degree courses and has a long and significant history. The exchange aims to expose students to contemporary perceptions and practices in photography so they could place their own photographic practice within a global context. The display opened on 13th July at 5:00 pm with an introduction in the Auditorium, and continued till the 16th of July in the Aquarium.',
    ],
  },
  {
    slug: 'kgs-raza-in-ahmedabad',
    date: 'Mar 2009',
    tag: 'Exhibition',
    title: 'KGS & Raza in Ahmedabad',
    venue: 'Amdavad ni Gufa (Hussain Doshi Gufa), Ahmedabad',
    desc: 'K. G. Subramanyan and S. H. Raza together at Amdavad ni Gufa, Ahmedabad — a rare meeting of two masters of Indian art, marked by an opening of paintings and prints.',
    originalHref: 'https://djmphotography.blogspot.com/2009/03/kgs-raza-in-ahmedabad.html',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh8_fD1msKpM43TiKoECqEYDXK9S0IHfzTIaKIzy7MLFZgI0oB7m671ufDeoAkzdpyVM_50gey9uL9UyCPrlyFtmZMYXVfNRcpllufjotysIqV1vCLnznrmRj-hnjEAR-qfof6YNHVVZXo/s1600/IMG_0123a.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhBrHbPd9BUcpUAKgLVQRSYSAIOzXvFL95cTuHp8a7FZy0q6PJvXborDL0tsJ1NfbJOlq4OLqP1-KeA7HdWeLHphBhiHL_cUen7H-GP0IzEhxDgPznnKVRaedZZ8ngxMH6hHDC6rdOChw0/s1600/IMG_0101a.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiCCxeqLupVD4gz_m9QWO9CS44V4VFqXbvizg08bVPbjTKTUT8KmVHUFX6OUqO6n-ZwAKL50md7e4Lhgz9zhpXKHZGACQUWO4PzX7rCtlPcoMopEerG63RaGSZRctEFPD9B_kvYIKiqYj8/s1600/IMG_0069a.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhjYVu2rSyIW5qfx_xcO3iYSh8hH1CT4Lr6foLR-z1rDbI4FpocflND5deZtRDHGbvYB8dEzS78Xr-NS_KRnfRez5Id8hHwvrGquous0zkRlBNVDrdJ7l7HopYGQWZrujeuFHg3K0qotOs/s1600/IMG_0068a.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhDEZPeHHGoq_Gt3Y5KnulprxWe7M_2y8c12CrKmc2RqqzyE5Uyo7_aE-22jgLoPV2qHvuFVVL9VwRicebpuFNXcfmNPxFHrJA8pkOaCi_EOpgUiR0mrMu3ZptDYb3M8VUjm4oomoGEN_s/s1600/IMG_0062a.jpg',
    ],
    paragraphs: [
      'Ahmedabad got a rare opportunity to meet two masters at the same venue. An exhibition of paintings and prints opened at Amdavad ni Gufa (Hussain Doshi Gufa). K. G. Subramanyan — Mani da — was there to open the show, and S. H. Raza was there to attend it. People were busy taking pictures and autographs, and the show was followed by a film on Mani da. It was a once-in-a-kind opportunity for art lovers to meet these two great masters — what stayed with me most was the simplicity of these people.',
    ],
  },
  {
    slug: 'rahul-nid',
    date: 'Jan 2009',
    tag: 'Portrait',
    title: 'Rahul @ NID',
    venue: 'National Institute of Design',
    desc: 'A portrait series photographed at the National Institute of Design.',
    originalHref: 'https://djmphotography.blogspot.com/2009/01/rahul-nid.html',
    images: [
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhOrYaSBUKzztSsIRwDvUoR1T56QbgoAqliFceMDBGFhW-GQYhf8AH6nqJNpv0mmWddjoM1eTWyqA6HIUMAlrcNBsMbepAL2kUd9dqWi03kSzQPgnBxeE5N7NBHiYmBG3-wiJQ2mVBJflc/s1600/_DJM2669.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhze9EG4hfpb8s1BkoRanxwClxfpLNvQ5nyIUdX-e0pLVKIRh5VVOTLDucxKFcDzRxA5_L8fYuTaZj6ch7H8U5Q9zxsrd9Ua7rmLX3s48FVceVTxz0QTwqiWXgATloTmiGoasEwHalCnRw/s1600/_DJM2594.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjk12VsNoh42tuIbDVsw-1P5dItzXPKWLOjXnR_YrxJz6VJSivciwH5ayj4S6Fq5qAxhNskYFMJ7oL2G9sOkamyyFtBDYnVZQOOL771ieGogTO7OxpXvESaHRUy8_SgPid5-3joR74ud7s/s1600/_DJM2509a.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgIeoH7Bz1QegpUOgw2Mwj5yR8WyITI5XA-GWIIwAvLoII_U_PqhNWAIttAgxrCb_YIpa3PaQ5Y6FN5kHOj0M4tF0M0JTH2_B_B6CQR1bkPEcMno6sDMZjZ_gX3E14hyphenhyphenTVgtGd96VHxdsc/s1600/_DJM2857.jpg',
      'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgBaJp2iauPl5gquCI1-OL1B34LswQBrl76C_iYhnLXkIG29TTTKigFJVNx_d7iyOgFopNiln-sklg1O4MT3SA41_vkWwIRsXV0ZHwOBhVV6l3R3UDc8uO5YaLozeIAs-P3sgoMxNEw8OI/s1600/_DJM2922.jpg',
    ],
    paragraphs: [
    ],
  },
]
